module.exports = {
    name: process.env.APP_NAME || 'Laravel',
    env: process.env.APP_ENV || 'production',
    debug: process.env.APP_DEBUG === 'true',
    debug_blacklist: {
        _ENV: [
            'APP_KEY',
            'DB_PASSWORD',
            'REDIS_PASSWORD',
            'MAIL_PASSWORD',
            'PUSHER_APP_KEY',
            'PUSHER_APP_SECRET',
        ],
        _SERVER: [
            'APP_KEY',
            'DB_PASSWORD',
            'REDIS_PASSWORD',
            'MAIL_PASSWORD',
            'PUSHER_APP_KEY',
            'PUSHER_APP_SECRET',
        ],
        _POST: [
            'password',
        ],
    },

    url: process.env.APP_URL || 'http://localhost',
    timezone: process.env.APP_TIMEZONE || 'UTC',
    locale: process.env.DEFAULT_LANGUAGE || 'en',
    fallback_locale: 'en',
    key: process.env.APP_KEY,
    cipher: 'AES-256-CBC',
    providers: [
        require('Illuminate/Auth/AuthServiceProvider').default,
        require('Illuminate/Broadcasting.js/BroadcastServiceProvider').default,
        require('Illuminate\\Bus\\BusServiceProvider').default,
        require('Illuminate\\Cache\\CacheServiceProvider').default,
        require('Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider').default,
        require('Illuminate\\Cookie\\CookieServiceProvider').default,
        require('Illuminate\\Database\\DatabaseServiceProvider').default,
        require('Illuminate\\Encryption\\EncryptionServiceProvider').default,
        require('Illuminate\\Filesystem\\FilesystemServiceProvider').default,
        require('Illuminate\\Foundation\\Providers\\FoundationServiceProvider').default,
        require('Illuminate\\Hashing\\HashServiceProvider').default,
        require('Illuminate\\Mail\\MailServiceProvider').default,
        require('Illuminate\\Notifications\\NotificationServiceProvider').default,
        require('Illuminate\\Pagination\\PaginationServiceProvider').default,
        require('Illuminate\\Pipeline\\PipelineServiceProvider').default,
        require('Illuminate\\Queue\\QueueServiceProvider').default,
        require('Illuminate\\Redis\\RedisServiceProvider').default,
        require('Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider').default,
        require('Illuminate\\Session\\SessionServiceProvider').default,
        require('Illuminate\\Translation\\TranslationServiceProvider').default,
        require('Illuminate\\Validation\\ValidationServiceProvider').default,
        require('Illuminate\\View\\ViewServiceProvider').default,
        require('Laracon21\\Colorcodeconverter\\ColorcodeconverterServiceProvider').default,
/*
        Laracasts\Flash\FlashServiceProvider::class,
        Laravel\Socialite\SocialiteServiceProvider::class,
        Laracon21\Timezones\TimezonesServiceProvider::class,
        niklasravnsborg\LaravelPdf\PdfServiceProvider::class,
        Unicodeveloper\Paystack\PaystackServiceProvider::class,
        MehediIitdu\CoreComponentRepository\CoreComponentRepositoryServiceProvider::class,
        Laracon21\Combinations\CombinationsServiceProvider::class,
        Maatwebsite\Excel\ExcelServiceProvider::class,
        Anand\LaravelPaytmWallet\PaytmWalletServiceProvider::class,
        \Laravel\Passport\PassportServiceProvider::class,
        KingFlamez\Rave\RaveServiceProvider::class,
        Intervention\Image\ImageServiceProvider::class,

        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
 */
    ],

    aliases: [
/*
        'App' => Illuminate\Support\Facades\App::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Broadcast' => Illuminate\Support\Facades\Broadcast::class,
        'Bus' => Illuminate\Support\Facades\Bus::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Config' => Illuminate\Support\Facades\Config::class,
        'Cookie' => Illuminate\Support\Facades\Cookie::class,
        'Crypt' => Illuminate\Support\Facades\Crypt::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
        'Event' => Illuminate\Support\Facades\Event::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Lang' => Illuminate\Support\Facades\Lang::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Notification' => Illuminate\Support\Facades\Notification::class,
        'Password' => Illuminate\Support\Facades\Password::class,
        'Queue' => Illuminate\Support\Facades\Queue::class,
        'Redirect' => Illuminate\Support\Facades\Redirect::class,
        'Redis' => Illuminate\Support\Facades\Redis::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response' => Illuminate\Support\Facades\Response::class,
        'Route' => Illuminate\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,
        'Socialite' => Laravel\Socialite\Facades\Socialite::class,
        'PDF' => niklasravnsborg\LaravelPdf\Facades\Pdf::class,
        'Paystack' => Unicodeveloper\Paystack\Facades\Paystack::class,
        'Excel' => Maatwebsite\Excel\Facades\Excel::class,
        'PaytmWallet' => Anand\LaravelPaytmWallet\Facades\PaytmWallet::class,
        'Str' => Illuminate\Support\Str::class,
        'Rave' => KingFlamez\Rave\Facades\Rave::class,
        'Image' => Intervention\Image\Facades\Image::class
 */
    ]
}